export { ActionSheetMock }              from './mocks/action-sheet';
export { ActionSheetControllerMock }    from './mocks/action-sheet-controller';
export { AlertMock }                    from './mocks/alert';
export { AlertControllerMock }          from './mocks/alert-controller';
export { AppMock }                      from './mocks/app';
export { ContentMock }                  from './mocks/content';
export { EventsMock }                   from './mocks/events';
export { HapticMock }                   from './mocks/haptic';
export { KeyboardMock }                 from './mocks/keyboard';
export { LoadingMock }                  from './mocks/loading';
export { LoadingControllerMock }        from './mocks/loading-controller';
export { MenuMock }                     from './mocks/menu';
export { MenuControllerMock }           from './mocks/menu-controller';
export { ModalMock }                    from './mocks/modal';
export { ModalControllerMock }          from './mocks/modal-controller';
export { NavControllerMock }            from './mocks/nav-controller';
export { NavParamsMock}                 from './mocks/nav-params';
export { TabMock }                      from './mocks/tab';
export { TabsMock }                     from './mocks/tabs';
export { InfiniteScrollMock }           from './mocks/inifinite-scroll';
export { PlatformMock }                 from './mocks/platform';
export { PopoverMock }                  from './mocks/popover';
export { PopoverControllerMock }        from './mocks/popover-controller';
export { ToastMock }                    from './mocks/toast';
export { ToastControllerMock }          from './mocks/toast-controller';
export { SlidesMock }                   from './mocks/slides';

